vich_uploader:
    db_driver: orm

    mappings:
        categories:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        etablissements:
            uri_prefix: /uploads/etablissements
            upload_destination: '%kernel.project_dir%/public/uploads/etablissements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

